// React/src/App.js
import { DetailsView, FileManagerComponent, NavigationPane, Toolbar, Inject } from '@syncfusion/ej2-react-filemanager';
import { PdfViewerComponent } from '@syncfusion/ej2-react-pdfviewer';
import { DocumentEditorContainerComponent } from '@syncfusion/ej2-react-documenteditor';
import { SpreadsheetComponent } from '@syncfusion/ej2-react-spreadsheet';
import * as React from 'react';
import './App.css';

function App() {
    function onfileOpen(args) {

        const fileName = args.fileDetails.name;
        const filePath = args.fileDetails.filterPath.replace(/\\/g, "/") + fileName;
        const fileType = args.fileDetails.type;

        switch (fileType) {
            case ".docx":
            case ".txt":
            case ".html":
            case ".rtf":
            case ".xml":
                showDocViewer( fileName );
                getFileStream(filePath, false);
                break;
            case ".pdf":
                showPDFViewer(fileName);
                getFileStream(filePath, true);
                break;
            case ".csv":
                showExcelViewer( fileName );
                getBlob(filePath, fileName, fileType);
                break;
            case ".pptx":
                showPDFViewer(fileName );
                convertPptToPdf(filePath, fileName);
                break;
            default:
                console.error(`Unsupported file type: ${fileType}`);
        }
    }
    function showDocViewer(name) {
        document.getElementsByClassName("doc-title")[0].innerHTML = name;
        (document.getElementsByClassName("file-container")[0]).style.visibility = "hidden";
        (document.getElementsByClassName("doc-container")[0]).style.visibility = "visible";
    }

    //Shows the PDF viewer

    function showPDFViewer(name) {
        (document.getElementsByClassName("file-container")[0]).style.visibility = "hidden";
        (document.getElementsByClassName("pdf-container")[0]).style.visibility = "visible";
        document.getElementsByClassName("pdf-title")[0].innerHTML = name;
    }
    function showExcelViewer(name) {
        (document.getElementsByClassName("file-container")[0]).style.visibility = "hidden";
        (document.getElementsByClassName("excel-container")[0]).style.visibility = "visible";
        document.getElementsByClassName("excel-title")[0].innerHTML = name;
    }

    // sends HTTPPost Request to read the file as fileStream.

    function getFileStream(filePath, isPDF) {
        let ajax = new XMLHttpRequest();
        ajax.open("POST", hostUrl + "api/FileManager/GetDocument", true);
        ajax.setRequestHeader("content-type", "application/json");
        ajax.onreadystatechange = () => {
            if (ajax.readyState === 4) {
                if (ajax.status === 200 || ajax.status === 304) {
                    if (!isPDF) {
                        docObj.documentEditor.open(ajax.responseText);
                    } else {
                        pdfObj.load(ajax.responseText, null);
                    }
                }
            }
        };
        ajax.send(JSON.stringify({ "FileName": filePath, "Action": (!isPDF ? "ImportFile" : "LoadPDF") }));
    }

    function getBlob(filePath, fileName, fileType) {
        let request = new XMLHttpRequest();
        request.responseType = 'blob';
        request.onload = () => {
            let file = new File([request.response], fileName);
            spreadsheetObj.open({ file: file });
        };
        request.open(
            'GET',
            hostUrl + 'api/FileManager/GetExcel' + '?FileName=' + filePath
        );
        request.send();
    }

    function convertPptToPdf(filePath, fileName) {
        fetch('http://localhost:{port}/api/FileManager/ConvertPptToPdf', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ FilePath: filePath }), // Send file path to backend
        })
            .then((response) => {
                if (!response.ok) {
                    throw new Error('Failed to convert PPT to PDF');
                }
                return response.blob(); // Get the PDF blob
            })
            .then((blob) => {
                const pdfUrl = URL.createObjectURL(blob); // Create a URL for the PDF blob
                showPDFViewer(fileName);
                pdfObj.load(pdfUrl, '');
            })
            .catch((error) => {
                console.error('Error converting PPT to PDF:', error);
            });
    }
    function closeView() {
        (document.getElementsByClassName("file-container")[0]).style.visibility = "visible";
        (document.getElementsByClassName("doc-container")[0]).style.visibility = "hidden";
        (document.getElementsByClassName("pdf-container")[0]).style.visibility = "hidden";
        (document.getElementsByClassName("excel-container")[0]).style.visibility = "hidden";
    }
    let pdfObj;
    let docObj;
    let spreadsheetObj;
    let hostUrl = "http://localhost:{port}/";
    return (<><div className="control-section">
        <div className="file-container">
        <FileManagerComponent id="file"
            ajaxSettings={{
                // Replace the hosted port number in the place of "{port}"
                url: hostUrl + "api/FileManager/FileOperations",
                downloadUrl: hostUrl + 'api/FileManager/Download',
                getImageUrl: hostUrl + "api/FileManager/GetImage",
                uploadUrl: hostUrl + 'api/FileManager/Upload'
            }}
            fileOpen={onfileOpen.bind(this)}>
            <Inject services={[NavigationPane, DetailsView, Toolbar]} />
        </FileManagerComponent>
        </div>
    </div>
    <div className="pdf-container hidden container">
        <span className="pdf-title"></span>
        <button onClick={closeView.bind(this)}>Close</button>
        <PdfViewerComponent id="pdfViewer" ref={s => (pdfObj = s)}
            serviceUrl="https://ej2services.syncfusion.com/production/web-services/api/pdfviewer">
        </PdfViewerComponent>
    </div>
    <div className="doc-container hidden container">
        <span className="doc-title"></span>
        <button onClick={closeView.bind(this)}>Close</button>
        <DocumentEditorContainerComponent id="docEditor" ref={s => (docObj = s)} />
    </div>
    <div className="excel-container hidden container">
        <span className="excel-title"></span>
        <button onClick={closeView.bind(this)}>Close</button>
        <SpreadsheetComponent id="spreadsheet" ref={s => (spreadsheetObj = s)} openUrl="http://localhost:{port}/api/FileManager/OpenExcel"></SpreadsheetComponent>
    </div>
    </>);
}
export default App;

// Vue/src/App.vue
<template>
<div id="app">
    <div class="control-section">
    <div class="file-container">
     <ejs-filemanager id="overview_filemanager" :ajaxSettings="ajaxSettings" :fileOpen='onfileOpen'>
     </ejs-filemanager>
    </div>
    <div class="pdf-container hidden container">
      <span class="pdf-title"></span>
      <button v-on:click="closeView">Close</button>
      <ejs-pdfviewer id="pdfViewer" ref="pdfViewer" :serviceUrl="serviceUrl"></ejs-pdfviewer>
    </div>

    <div class="doc-container hidden container">
      <span class="doc-title"></span>
      <button v-on:click="closeView" >Close</button>
      <ejs-documenteditorcontainer id="docViewer" ref="docViewer"></ejs-documenteditorcontainer >
    </div>

    <div class="excel-container hidden container">
      <span class="excel-title"></span>
      <button v-on:click="closeView" >Close</button>
      <ejs-spreadsheet id="excelViewer"  ref="excelViewer" :openUrl="openUrl"></ejs-spreadsheet>
    </div>
</div>
</div>
</template>
<script>
import { FileManagerComponent, DetailsView, NavigationPane, Toolbar } from "@syncfusion/ej2-vue-filemanager";
import { PdfViewerComponent } from "@syncfusion/ej2-vue-pdfviewer";
import { DocumentEditorContainerComponent } from "@syncfusion/ej2-vue-documenteditor";
import { SpreadsheetComponent } from "@syncfusion/ej2-vue-spreadsheet";
import { enableRipple } from "@syncfusion/ej2-base";

enableRipple(true);
let hostUrl = 'http://localhost:{port}/';

export default {
    name: "App",
    components: {
        "ejs-filemanager":FileManagerComponent,
        "ejs-pdfviewer":PdfViewerComponent,
        "ejs-documenteditorcontainer":DocumentEditorContainerComponent,
        "ejs-spreadsheet":SpreadsheetComponent
    },
     data () {
      return {
        ajaxSettings:
        {
          url: hostUrl + 'api/FileManager/FileOperations',
          getImageUrl: hostUrl + 'api/FileManager/GetImage',
          uploadUrl: hostUrl + 'api/FileManager/Upload',
          downloadUrl: hostUrl + 'api/FileManager/Download'
        },
        serviceUrl: 'https://ej2services.syncfusion.com/production/web-services/api/pdfviewer',
        openUrl : 'http://localhost:{port}/api/FileManager/OpenExcel'
      }
    },
    methods: {
      onfileOpen: function (args) {
        let fileName = args.fileDetails.name;
        let filePath = args.fileDetails.filterPath.replace(/\\/g, "/") + fileName;
        let fileType = args.fileDetails.type;
        switch (fileType) {
            case ".docx":
            case ".txt":
            case ".html":
            case ".rtf":
            case ".xml":
                this.showDocViewer(fileName);
                this.getFileStream(filePath, false);
                break;

            case ".pdf":
                this.showPDFViewer(fileName);
                this.getFileStream(filePath, true);
                break;

            case ".csv":
                this.showExcelViewer(fileName);
                this.getBlob(filePath, fileName, fileType);
                break;

            case ".pptx":
                this.showPDFViewer(fileName);
                this.convertPptToPdf(filePath, fileName);
                break;

            default:
                console.log("File type not supported");
        }
      },
      showDocViewer: function(name) {
          document.getElementsByClassName("doc-title")[0].innerHTML = name;
          (document.getElementsByClassName("file-container")[0]).style.visibility = "hidden";
          (document.getElementsByClassName("doc-container")[0]).style.visibility = "visible";
      },
      showPDFViewer: function(name) {
          (document.getElementsByClassName("file-container")[0]).style.visibility = "hidden";
          (document.getElementsByClassName("pdf-container")[0]).style.visibility = "visible";
          document.getElementsByClassName("pdf-title")[0].innerHTML = name;
      },
      showExcelViewer: function(name) {
          (document.getElementsByClassName("file-container")[0]).style.visibility = "hidden";
          (document.getElementsByClassName("excel-container")[0]).style.visibility = "visible";
          document.getElementsByClassName("excel-title")[0].innerHTML = name;
      },
      getFileStream: function(filePath, isPDF) {
          let ajax = new XMLHttpRequest();
          ajax.open("POST", hostUrl + "api/FileManager/GetDocument", true);
          ajax.setRequestHeader("content-type", "application/json");
          ajax.onreadystatechange = () => {
              if (ajax.readyState === 4) {
                  if (ajax.status === 200 || ajax.status === 304) {
                      if (!isPDF) {
                          this.$refs.docViewer.ej2Instance.documentEditor.open(ajax.responseText);
                      } else {
                          this.$refs.pdfViewer.load(ajax.responseText, null);
                      }
                  }
              }
          };
          ajax.send(JSON.stringify({ "FileName": filePath, "Action": (!isPDF ? "ImportFile" : "LoadPDF") }));
      },
      getBlob: function(filePath, fileName) {
          let request = new XMLHttpRequest();
          request.responseType = 'blob';
          request.onload = () => {
              let file = new File([request.response], fileName);
              this.$refs.excelViewer.open({ file: file });
          };
          request.open(
              'GET',
              hostUrl + 'api/FileManager/GetExcel' + '?FileName=' + filePath
          );
          request.send();
      },
      convertPptToPdf:function (filePath, fileName) {
          fetch('http://localhost:{port}/api/FileManager/ConvertPptToPdf', {
              method: 'POST',
              headers: {
                  'Content-Type': 'application/json',
              },
              body: JSON.stringify({ FilePath: filePath }), // Send file path to backend
          })
              .then((response) => {
                  if (!response.ok) {
                      throw new Error('Failed to convert PPT to PDF');
                  }
                  return response.blob(); // Get the PDF blob
              })
              .then((blob) => {
                  const pdfUrl = URL.createObjectURL(blob); // Create a URL for the PDF blob
                  this.showPDFViewer(fileName);
                  this.$refs.pdfViewer.load(pdfUrl, '');
              })
              .catch((error) => {
                  console.error('Error converting PPT to PDF:', error);
              });
      },
      closeView:function() {
        (document.getElementsByClassName("file-container")[0]).style.visibility = "visible";
        (document.getElementsByClassName("doc-container")[0]).style.visibility = "hidden";
        (document.getElementsByClassName("pdf-container")[0]).style.visibility = "hidden";
        (document.getElementsByClassName("excel-container")[0]).style.visibility = "hidden";
      }
    },
    //Injecting additional modules in FileManager
    provide: {
      filemanager: [DetailsView, NavigationPane, Toolbar]
    }
}
</script>
<style>
@import "../node_modules/@syncfusion/ej2-base/styles/material.css";
@import "../node_modules/@syncfusion/ej2-icons/styles/material.css";
@import "../node_modules/@syncfusion/ej2-inputs/styles/material.css";
@import "../node_modules/@syncfusion/ej2-popups/styles/material.css";
@import "../node_modules/@syncfusion/ej2-buttons/styles/material.css";
@import "../node_modules/@syncfusion/ej2-splitbuttons/styles/material.css";
@import "../node_modules/@syncfusion/ej2-navigations/styles/material.css";
@import "../node_modules/@syncfusion/ej2-layouts/styles/material.css";
@import "../node_modules/@syncfusion/ej2-grids/styles/material.css";
@import "../node_modules/@syncfusion/ej2-vue-filemanager/styles/material.css";
@import "../node_modules/@syncfusion/ej2-documenteditor/styles/material.css";
@import '../node_modules/@syncfusion/ej2-pdfviewer/styles/material.css';
@import '../node_modules/@syncfusion/ej2-spreadsheet/styles/material.css';
  .file-container {
    height:100%;
    width:100%;
  }
  .title-container {
    background-color: #eee;
    height: 22px;
  }
  .doc-container, .pdf-container, .excel-container {
    height:100%;
    width:100%;
    position: absolute;
    top: 0;
    visibility: hidden;
  }
  .close-button{
    float:right;
  }
  body,html{
    margin:0;
    height:100%;
    width:100%;
  }
</style>
